services:
  db:
    image: mysql:lts
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pet_password
      MYSQL_DATABASE: petdb
      MYSQL_USER: backend_user
      MYSQL_PASSWORD: backend_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
