spring.application.name=Pet Backend

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql= true

# Liquibase
spring.liquibase.enabled= true
spring.liquibase.change-log= classpath:/db/migration/db.changelog-master.xml

# RSA
jwt.public.key=classpath:keys/public_key.pem
jwt.private.key=classpath:keys/private_key.pem